source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AccountPod_Example', :exclusive => true do
  pod 'AccountPod', :path => '../'
end

target 'AccountPod_Tests', :exclusive => true do
  pod 'AccountPod', :path => '../'

  
end
